"""
Emit an ATT&CK Navigator layer (v4.5) from a coverage model, so the same data
can be loaded into the official navigator (https://mitre-attack.github.io/attack-navigator/).

Each technique the detections address gets a score equal to its detection count,
and the gradient runs white → blue so denser coverage reads darker. Sub-technique
ids are emitted alongside their parents so the navigator colors both.
"""

from __future__ import annotations

from . import attack_data as ad

_GRADIENT = ["#ffffff", "#66b1ff", "#0b3d91"]


def build_layer(coverage: dict) -> dict:
    count_by_id: dict[str, int] = coverage.get("_count_by_id", {})
    max_score = max(count_by_id.values(), default=1)

    techniques = []
    for tid, count in sorted(count_by_id.items()):
        if not ad.is_known(tid):
            continue
        techniques.append({
            "techniqueID": tid,
            "score": count,
            "comment": f"{count} detection(s) in portfolio",
            "enabled": True,
        })

    return {
        "name": coverage.get("layer_name", "Portfolio detection coverage"),
        "versions": {"attack": "15", "navigator": "4.9.1", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": (
            "Detection coverage generated by attack-coverage-tracker from the "
            "portfolio's Defender, Sentinel, and Sigma detections."
        ),
        "sorting": 0,
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {"colors": _GRADIENT, "minValue": 0, "maxValue": max(max_score, 1)},
        "legendItems": [
            {"label": "1 detection", "color": _GRADIENT[1]},
            {"label": f"{max(max_score,1)}+ detections", "color": _GRADIENT[2]},
        ],
        "metadata": [
            {"name": "detections_parsed", "value": str(coverage["summary"]["detections_parsed"])},
            {"name": "techniques_covered", "value": str(coverage["summary"]["techniques_covered"])},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
    }
